@startuml

title __CRUDOPERATIONS's Class Diagram__\n

  namespace  {
    namespace om.weddingplanner.server {
      namespace model {
        namespace crudoperations {
          interface com.weddingplanner.server.services.crudoperations.AdminRepo {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.weddingplanner.server {
      namespace model {
        namespace crudoperations {
          interface com.weddingplanner.server.services.crudoperations.AdvertisementRepo {
              {abstract} + findByBusinessOwner()
              {abstract} + updateAdvertisementDetails()
              {abstract} + updateScore()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.weddingplanner.server {
      namespace model {
        namespace crudoperations {
          interface com.weddingplanner.server.services.crudoperations.BusinessOwnerRepo {
              {abstract} + updateAccountStatus()
              {abstract} + updateProfileDetails()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.weddingplanner.server {
      namespace model {
        namespace crudoperations {
          interface com.weddingplanner.server.services.crudoperations.CustomerRepo {
              {abstract} + updateCustomerStatus()
              {abstract} + updateProfileDetails()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.weddingplanner.server {
      namespace model {
        namespace crudoperations {
          interface com.weddingplanner.server.services.crudoperations.InquiryRepo {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.weddingplanner.server {
      namespace model {
        namespace crudoperations {
          interface com.weddingplanner.server.services.crudoperations.ReviewRepo {
              {abstract} + findByAdvertisementId()
              {abstract} + findByEmail()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.weddingplanner.server {
      namespace model {
        namespace crudoperations {
          interface com.weddingplanner.server.services.crudoperations.SystemUserRepository {
              {abstract} + findByEmail()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
