@startuml

title __SERVICES's Class Diagram__\n

  namespace  {
    namespace om.weddingplanner.server {
      namespace services {
        interface com.weddingplanner.server.services.AdvertisementService {
            {abstract} + listAdvertisements()
            {abstract} + searchAdvertisementsByUser()
            {abstract} + updateAdvertisementDetails()
            {abstract} + updateAdvertisementRating()
        }
      }
    }
  }
  

  namespace  {
    namespace om.weddingplanner.server {
      namespace services {
        interface com.weddingplanner.server.services.GeneralServices {
            {abstract} + add()
            {abstract} + removeById()
            {abstract} + retrieveById()
        }
      }
    }
  }
  

  namespace  {
    namespace om.weddingplanner.server {
      namespace services {
        interface com.weddingplanner.server.services.InquiryService {
            {abstract} + addInquiry()
            {abstract} + getInquiry()
            {abstract} + listInquiries()
            {abstract} + removeInquiry()
        }
      }
    }
  }
  

  namespace  {
    namespace om.weddingplanner.server {
      namespace services {
        class com.weddingplanner.server.services.MyUserDetailsServiceImpl {
            + loadUserByUsername()
        }
      }
    }
  }
  

  namespace  {
    namespace om.weddingplanner.server {
      namespace services {
        interface com.weddingplanner.server.services.ReviewService {
            {abstract} + addReview()
            {abstract} + deleteReview()
            {abstract} + getReview()
            {abstract} + listReviewByAdvertisement()
            {abstract} + listReviewsByUser()
            {abstract} + removeReview()
        }
      }
    }
  }
  

  namespace  {
    namespace om.weddingplanner.server {
      namespace services {
        interface com.weddingplanner.server.services.UserService {
            {abstract} + addAdminUser()
            {abstract} + addBusinessOwner()
            {abstract} + addCustomer()
            {abstract} + getBusiness()
            {abstract} + getCustomer()
            {abstract} + isUserRegistered()
            {abstract} + listBusinessOwners()
            {abstract} + listCustomers()
            {abstract} + removeBusinessOwner()
            {abstract} + removeCustomer()
            {abstract} + searchBusinessOwner()
            {abstract} + updateBusinessAccountStatus()
            {abstract} + updateBusinessOwnerProfile()
            {abstract} + updateCustomerProfile()
            {abstract} + updateCustomerStatus()
        }
      }
    }
  }
  

  com.weddingplanner.server.services.MyUserDetailsServiceImpl .up.|> org.springframework.security.core.userdetails.UserDetailsService
  com.weddingplanner.server.services.MyUserDetailsServiceImpl o-- com.weddingplanner.server.services.crudoperations.SystemUserRepository : userRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
